Verify outputs

diff --git a/.github/workflows/pr-open.yml b/.github/workflows/pr-open.yml
--- a/.github/workflows/pr-open.yml
+++ b/.github/workflows/pr-open.yml
@@ -16,7 +16,8 @@ jobs:
     runs-on: ubuntu-24.04
     steps:
       - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
-      - uses: ./
+      - id: build
+        uses: ./
         with:
           package: backend
           keep_versions: 10
@@ -25,6 +26,15 @@ jobs:
             ${{ github.event.number }}
             ${{ github.event.number }}-multiline
             pr-latest
+
+      - if: steps.build.outputs.triggered != 'false'
+        run: |
+          # Verify outputs
+          echo "Outputs: ${{ toJSON(steps.build.outputs) }}"
+          if [ "${{ steps.build.outputs.digest }}" != "true" ]|| [ "${{ steps.build.outputs.triggered }}" != "true" ]; then
+            echo "Error!  Verify outputs."
+            exit 1
+          fi
 
   # Anything can be retagged if a fallback image exists (e.g. test)
   retag:
@@ -35,7 +45,8 @@ jobs:
     runs-on: ubuntu-24.04
     steps:
       - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
-      - uses: ./
+      - id: retag
+        uses: ./
         with:
           package: backend
           keep_versions: 10
@@ -44,6 +55,14 @@ jobs:
           tag_fallback: test
           triggers: ('backend/')
 
+      - if: steps.retag.outputs.triggered != 'false'
+        run: |
+          # Verify outputs
+          echo "Outputs: ${{ toJSON(steps.retag.outputs) }}"
+          if [ "${{ steps.retag.outputs.digest }}" != "true" ]|| [ "${{ steps.retag.outputs.triggered }}" != "true" ]; then
+            echo "Error!  Verify outputs."
+            exit 1
+          fi
 
   # FOM apps build from repo root, above their Dockerfiles (extra params)
   advanced:
@@ -53,7 +72,8 @@ jobs:
     runs-on: ubuntu-24.04
     steps:
       - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
-      - uses: ./
+      - id: advanced
+        uses: ./
         with:
           package: api
           build_context: .
@@ -61,3 +81,12 @@ jobs:
           keep_versions: 10
           repository: bcgov/nr-fom
           tags: ${{ github.event.number }}
+
+      - if: steps.advanced.outputs.triggered != 'false'
+        run: |
+          # Verify outputs
+          echo "Outputs: ${{ toJSON(steps.advanced.outputs) }}"
+          if [ "${{ steps.advanced.outputs.digest }}" != "true" ]|| [ "${{ steps.advanced.outputs.triggered }}" != "true" ]; then
+            echo "Error!  Verify outputs."
+            exit 1
+          fi
